---
- block:
  - name: ensure PVEs home exits
    file: path='{{ pves_home }}' state=directory
        owner='{{ ansible_remote_user }}' group='{{ web_app_group }}'

  - name: ensure project directory exists
    file:
      path: "{{ backend_project_dir }}"
      state: directory
      owner: "{{ ansible_remote_user }}"
      group: "{{ web_app_group }}"

  - name: ensure logs directory exists
    file: path='{{ logs_home }}' state=directory owner='{{ web_app_user }}'
      group='{{ web_app_group }}'

  - name: ensure target directory for static exists
    file: path='{{ backend_static_dir }}' state=directory
        owner='{{ ansible_remote_user }}' group='{{ web_app_group }}'
