- block:
  - name: ensure varnish in package.keywords
    template: src=varnish.j2
        dest='{{ package_keywords_dir }}/varnish'
        owner=root group=root mode=0644
    register: varnish_in_keywords

  - name: ensure varnish package installed
    portage: package=varnish state=present update=yes quiet=yes
    register: varnish_installed

  - name: check varnish secret file exists
    stat: path='{{ varnish_secret_file }}' get_md5=no
    register: varnish_secret_exists

  - name: make varnish secret file
    command: /bin/dd if=/dev/random of='{{ varnish_secret_file }}' count=1
    args:
      chdir: '{{ varnish_config_dir }}'
    when: not varnish_secret_exists.stat.exists
    register: varnish_secret_created

  - name: ensure varnishd in /etc/conf.d has proper options
    template: src=varnishd_options.j2
        dest='/etc/conf.d/varnishd'
        owner=root group=root mode=0644
    register: varnishd_options

  - name: ensure varnish configuration is up to date
    template: src={{ inventory_hostname }}.default.vcl
        dest='{{ varnish_config_dir }}/default.vcl'
        owner=root group=varnish mode=0644
    register: varnish_config

  - name: ensure varnish running
    service: name=varnishd state=started enabled=yes
    when: not varnish_installed.changed

  become: yes
