---
dependencies:
  - { role: sqlite, when: 'not quick' }
  - { role: varnish, when: 'not quick and not test' }
  - { role: certbot, when: 'not quick and not test' }
  - { role: nginx, when: 'not quick and not test' }
  - { role: supervisord, when: 'not quick and not test' }
  - { role: gulp, when: 'not quick and not test' }
