---
- name: setup python virtual environment for certbot
  pip:
    name: certbot-nginx
    virtualenv: '{{ certbot_pve }}'
    virtualenv_python: python{{certbot_python_version}}
  register: pve_created

- block:
  - name: ensure certbot will run twice a day
    cron:
      name: certbot timetable
      minute: 17
      hour: '*/12'
      user: root
      job: '{{ certbot_pve }}/bin/certbot renew --nginx --preferred-challenges
        tls-sni --quiet'

  become: yes
