---
- block:
  - name: ensure necessery keyword addition
    template: src=nodejs.keywords.j2
        dest='{{ package_keywords_dir }}/nodejs'
        owner=root group=root mode=0644
    register: nodejs_in_keywords

  - name: ensure NodeJS available
    portage: package=nodejs state=installed changed_use=yes quiet=yes
    register: nodejs_installed

  - name: upgrade global libraries
    script: scripts/npm-upgrade.sh
    when: nodejs_installed.changed

  - name: ensure Gulp installed globally
    npm: name=gulp global=yes state=present

  become: yes
