- name: Testing playbook
  hosts: '{{ target }}'
  gather_facts: no
  vars_files:
    - ../vars/common.yaml
  vars:
    mega_option: Bla-bla-bla
    ctx: '{{ mega_option }} - {{ inventory_hostname }}'

  tasks:
    - name: Create a file
      copy: content={{ ctx }}  dest=/tmp/dummy.txt
      tags: super

    - name: Test message
      debug: msg='Play as {{ ansible_remote_user }} on {{ inventory_hostname }}'
      tags: dummy
