---
- name: fetch kernel sources from git
  hosts: base
  roles:
  - kernel-sources

- name: update Linux kernel
  hosts: linux-kernel
  vars:
    cpus: '{{ ansible_processor_vcpus + 1 | int }}'
    grub: 1
  roles:
  - kernel-update
